plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
}

android {
    namespace = "com.parkit.app"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.parkit.app"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "0.1.0-demo"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

// Defaults to the emulator's host-loopback alias for local dev. Override for
// a build meant to run on a real device elsewhere:
// ./gradlew assembleDebug -PapiBaseUrl=https://your-tunnel-url/
//
// Deliberately NOT using AGP's buildConfigField here: that generates and
// compiles a BuildConfig.java, and javac — even for one trivial generated
// file — pulls in AGP's androidJdkImage transform, which needs a JDK with
// jlink. The only JDK on this machine that's new enough for this project's
// Gradle version (PyCharm's bundled JBR, 21) doesn't ship jlink; the one
// that does (Android Studio's JBR, 25) is too new for this Gradle version
// to run at all. Generating a plain .kt file sidesteps the whole javac path
// — kotlinc has no such dependency.
val apiBaseUrl = (project.findProperty("apiBaseUrl") as String?) ?: "http://10.0.2.2:8000/"
val generatedApiConfigDir = layout.buildDirectory.dir("generated/source/apiconfig")

val generateApiConfig = tasks.register("generateApiConfig") {
    // Without this, Gradle's up-to-date check has no idea the task's output
    // depends on apiBaseUrl, and happily skips re-running it when only the
    // property changes between builds — silently keeping a stale BASE_URL
    // baked into the APK. Caught this only by noticing a rebuilt APK was
    // still pointing at a tunnel URL from two builds ago.
    inputs.property("apiBaseUrl", apiBaseUrl)
    outputs.dir(generatedApiConfigDir)
    doLast {
        val dir = generatedApiConfigDir.get().dir("com/parkit/app").asFile
        dir.mkdirs()
        dir.resolve("ApiConfig.kt").writeText(
            """
            package com.parkit.app

            // Generated by the generateApiConfig Gradle task — do not edit.
            object ApiConfig {
                const val BASE_URL: String = "$apiBaseUrl"
            }
            """.trimIndent() + "\n",
        )
    }
}

android.sourceSets.getByName("main").kotlin.srcDir(generatedApiConfigDir)

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    dependsOn(generateApiConfig)
}

dependencies {
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.4")
    implementation("androidx.activity:activity-compose:1.9.1")

    val composeBom = platform("androidx.compose:compose-bom:2024.06.00")
    implementation(composeBom)
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended")
    implementation("androidx.navigation:navigation-compose:2.7.7")

    implementation("com.squareup.retrofit2:retrofit:2.11.0")
    implementation("com.squareup.retrofit2:converter-moshi:2.11.0")
    implementation("com.squareup.moshi:moshi-kotlin:1.15.1")
    implementation("com.squareup.okhttp3:logging-interceptor:4.12.0")

    implementation("org.osmdroid:osmdroid-android:6.1.20")
    implementation("io.coil-kt:coil-compose:2.6.0")

    debugImplementation("androidx.compose.ui:ui-tooling")
}
